headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\Mk\\Documents\\senamedicationwebapp\\backend\\.next"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Mk\\Documents\\senamedicationwebapp\\backend"
command = "next build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]