import { Schema, model } from 'mongoose';

export const UserSchema = new Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  resetPasswordToken: String,
  resetPasswordExpires: Date,
  isEmailVerified: { type: Boolean, default: false },
  emailVerificationToken: String,
  emailVerificationTokenExpires: Date,
  passwordResetToken: String,
  passwordResetTokenExpires: Date,
  phone: String,
  age: Number,
  gender: String,
  dateOfBirth: Date,
  profilePicture: String,
  address: String,
  emergencyContactName: String,
  emergencyContactPhone: String,
  bloodType: String,
  allergies: String,
  chronicConditions: String,
  currentMedications: String,
  medicalHistory: String,
  preferredLanguage: String,
  occupation: String,
  onboardingComplete: { type: Boolean, default: false },
  role: { type: String, default: 'user' },
  subscriptionPlan: String,
  medications: { type: Array, default: [] },
  trackedConditions: { type: Array, default: [] },
  activityLog: { type: Array, default: [] },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

export const UserMongoModel = model('User', UserSchema); 